![DSA_logo%20%28left%20align%29-1.png](attachment:DSA_logo%20%28left%20align%29-1.png)

# Numpy

In [ ]:
import numpy as np

In [ ]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## The Basics with Numpy

In [ ]:
height = [120,186,202,165,178,135]
weight = [39,78,129,55,65,40]
index = list(range(len(height)))
healthScore=[]

for i in index:
    healthScore.append(height[i]*weight[i])

    
print(healthScore)
print(type(healthScore))

[4680, 14508, 26058, 9075, 11570, 5400]
<class 'list'>


In [ ]:
height = np.array([120,186,202,165,178,135])
weight = np.array([39,78,129,55,65,40])

print(height*weight)
print(type(height*weight))

[ 4680 14508 26058  9075 11570  5400]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([1,2,3]) # One dimensional
a

array([1, 2, 3])

In [ ]:
a.size

3

In [ ]:
a.shape  # For one dimensional ( columnsize, )

(3,)

In [ ]:
a.ndim # Dimension size

1

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# Lists in List

myList1=[1,2,3]
myList2=[4,5,6]
myList3=[7,8,9]

fullList=[myList1,myList2,myList3]
fullList

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
fullList=[[1,2,3],[4,5,6],[7,8,9]]
fullList

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
b = np.array([[9.5,8.1,7.2],[6.1,5.7,4.5]]) # Two dimensional
b

array([[9.5, 8.1, 7.2],
       [6.1, 5.7, 4.5]])

In [ ]:
b2=np.array([
    [1,2,3],
    [4,5,6]
])
b2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape # For two dimensional ( rowsize, columnsize)

(2, 3)

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b.ndim # Dimension size

2

In [ ]:
b=b.astype(int) #Converting
b

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
c = np.array([[19,18,27.5],[34,51,44]])
c

array([[19. , 18. , 27.5],
       [34. , 51. , 44. ]])

In [ ]:
c.dtype

dtype('float64')

In [ ]:
d = np.array([[[1,2,2,99],[3,4,3,23],[3,4,3,4]],[[10,20,11,94],[30,44,17,24],[57,14,345,40]]])
d

array([[[  1,   2,   2,  99],
        [  3,   4,   3,  23],
        [  3,   4,   3,   4]],

       [[ 10,  20,  11,  94],
        [ 30,  44,  17,  24],
        [ 57,  14, 345,  40]]])

In [ ]:
d.shape # For two dimensional ( matrixsize, rowsize, columnsize)

(2, 3, 4)

In [ ]:
d.ndim # Dimension size

3

## Indexing and Slicing

In [ ]:
# Indexing 
fullList=[[1,2,3],[4,5,6],[7,8,9]]
fullList

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
fullList[0][2]

3

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a[1, 4] #Indexing [rowIndex,columnIndex]

12

In [ ]:
a[0, :] #Slicing  on column

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:, 2] # Slicing on row 

array([ 3, 10])

In [ ]:
a[0, 1:-1:2] #Slicing on column with steps

array([2, 4, 6])

In [ ]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [ ]:
a[:,2] = [30,40]
a

array([[ 1,  2, 30,  4,  5,  6,  7],
       [ 8,  9, 40, 11, 12, 20, 14]])

## Initializing Different Types of Arrays

In [ ]:
np.zeros((2,3)) # (rowsize, columnsize)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2)) # (matrixsize, rowsize, columnsize)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,2), 99) # ((rowsize, columnsize),value)

array([[99, 99],
       [99, 99]])

In [ ]:
myArray=np.array([[1,2],[23,44]])
myArray

array([[ 1,  2],
       [23, 44]])

In [ ]:
np.full_like(myArray, 4) # (numpyArray,value)

array([[4, 4],
       [4, 4]])

In [ ]:
np.random.rand(4,2) # (rowsize, columnsize)

array([[0.85554977, 0.73692951],
       [0.67321448, 0.28667543],
       [0.50360062, 0.13341296],
       [0.32507433, 0.34511538]])

In [ ]:
np.random.randint(-4,8,(3,3)) #  (startpoint,endpoint,(rowsize,columnsize))

array([[-4,  2, -3],
       [ 0, -4,  3],
       [ 4, -3,  1]])

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

In [ ]:
np.linspace(0,1,101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

## Mathematical operations on NumPy

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### With uFunctions

In [ ]:
a + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
a%2 #remainders

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [ ]:
a ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

##### With NumPy Artihmetic operations

In [ ]:
np.add(a,2) # addtion 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.subtract(a,2) # subtraction 

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.multiply(a,2) # subtraction 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.divide(a,2) # subtraction 

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
np.mod(a,2) # Remainders

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [ ]:
np.power(a,2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### 2 Vectors operations 

In [ ]:
# For multiple array operations each array have to be same column size

firstArray=np.array([1,2,3,4,5])
secondArray=np.array([6,7,8,9,10])

print("Addition =",firstArray+secondArray)
print("Subtraction =",firstArray-secondArray)
print("Multiplication =",firstArray*secondArray)
print("Division =",firstArray/secondArray)

Addition = [ 7  9 11 13 15]
Subtraction = [-5 -5 -5 -5 -5]
Multiplication = [ 6 14 24 36 50]
Division = [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


##### Other Mathematical Operations 

In [ ]:
# 1. np.sin(array) – Sine value
# 2. np.cos(array) – cosine value
# 3. np.log(array) – logarithm
# 4. np.log2(array) – logarithm from 2 
# 5. np.log10(array) – logarithm from 10
# 6. np.absolute(array) - Absoulute value
# 7. np.exp(array) – exponiental value from value degree

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

##### Other Statistical Operations 

In [ ]:
# 1. np.mean(array) – Arithmetical mean of all elements
# 2. np.sum(array) – Summary of all elements
# 3. np.min(array) – Minimum value of all elements
# 4. np.max(array) – Maximum value of all elements
# 5. np.std(array) – Standard deviation of all elements
# 6. np.median(array) – Median value of all elements

In [ ]:
np.mean(a)

5.5

In [ ]:
np.std(a)

2.8722813232690143

##### Sorting Numpy array

In [ ]:
v= np.array([2,3,4,7,1,5])
np.sort(v)

array([1, 2, 3, 4, 5, 7])

## Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3],[6,7,8]]) 
before

array([[1, 2, 3],
       [6, 7, 8]])

In [ ]:
before.size

6

In [ ]:
before.shape

(2, 3)

In [ ]:
after = before.reshape((3,2))
after

array([[1, 2],
       [3, 6],
       [7, 8]])

In [ ]:
after.shape

(3, 2)

In [ ]:
# Flatten any array 
after.ravel()

array([1, 2, 3, 6, 7, 8])

In [ ]:
# Transposing numpy array 

In [ ]:
myArray2=np.array([
    [1,2],
    [5,6],
    [3,4],
    [7,8],
    [10,11]
])
myArray2

array([[ 1,  2],
       [ 5,  6],
       [ 3,  4],
       [ 7,  8],
       [10, 11]])

In [ ]:
myArray2.T

array([[ 1,  5,  3,  7, 10],
       [ 2,  6,  4,  8, 11]])